DEFINE TEMP-TABLE {1} NO-UNDO SERIALIZE-NAME 'task':U
	FIELD nom_telefone AS CHARACTER INITIAL ? SERIALIZE-NAME 'phone':U
	FIELD num_id AS INTEGER INITIAL ? SERIALIZE-NAME 'id':U
	FIELD num_id_acao AS INTEGER INITIAL ? SERIALIZE-NAME 'actionId':U
    FIELD nom_acao AS CHARACTER INITIAL ? SERIALIZE-NAME 'actionName':U
	FIELD num_id_campanha AS INTEGER INITIAL ? SERIALIZE-NAME 'campaignId':U
    FIELD nom_campanha AS CHARACTER INITIAL ? SERIALIZE-NAME 'campaignName':U
    FIELD log_delete AS LOGICAL INITIAL FALSE SERIALIZE-NAME 'isDeleted':U
.
